### PR TITLE
Exports types, classes and interfaces

### PR DESCRIPTION
**Pull request by orgads**
### Checklist

- [x] Implement code
- [X] Commit message follows [commit guidelines](https://github.com/elastic/apm-agent-nodejs/blob/master/CONTRIBUTING.md#commit-message-guidelines)

### CODE REVIEW

**Comment by trentm** [comment]
Currently this fails the types tests -- `npm run test:types` -- with (from https://github.com/elastic/apm-agent-nodejs/pull/2141/checks?check_run_id=2994102567):

```
> elastic-apm-node@3.16.0 test:types /home/runner/work/apm-agent-nodejs/apm-agent-nodejs
> tsc --project test/types/tsconfig.json && tsc --project test/types/transpile/tsconfig.json && node test/types/transpile/index.js

Error: index.d.ts(5,1): error TS2309: An export assignment cannot be used in a module with other exported elements.
Error: test/types/index.ts(18,31): error TS2339: Property 'currentTraceIds' does not exist on type 'Agent'.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! elastic-apm-node@3.16.0 test:types: `tsc --project test/types/tsconfig.json && tsc --project test/types/transpile/tsconfig.json && node test/types/transpile/index.js`
```

My (limited) understanding is that one cannot add extra imports when already using `export =` (https://github.com/elastic/apm-agent-nodejs/blob/master/index.d.ts#L5).

Note that I have a draft start at updating our types to export more things here: https://github.com/elastic/apm-agent-nodejs/pull/2119   That is currently very incomplete, however.

**Comment by orgads** [comment]
Thank you. Closing then.
