### PR TITLE
test: fix tests to work with restify@9

### PR DESCRIPTION
**Pull request by trentm**
restify@9 was recently released. It only works with node >=v14.18.0
because it added use of https://nodejs.org/api/modules.html#core-modules
This updates restify testing to skip out when there is an incompat
(restify, node) version pair.

Note: It looks like the intent may have been for restify@9 to support
node >=10.0.0, so this may be refined later.

* * *

In this TAV CI test run the restify tests broke for node v8, v10, v12. Fine for node v14.
https://apm-ci.elastic.co/blue/organizations/jenkins/apm-agent-nodejs%2Fapm-agent-nodejs-mbp/detail/main/496/pipeline

```
[2022-11-16T06:55:02.428Z] node_tests_1  | -- installing ["restify@9.0.0"]
[2022-11-16T06:55:10.253Z] node_tests_1  | -- running test "node test/instrumentation/modules/restify/basic.test.js" with restify
[2022-11-16T06:55:10.655Z] node_tests_1  | internal/modules/cjs/loader.js:638
[2022-11-16T06:55:10.655Z] node_tests_1  |     throw err;
[2022-11-16T06:55:10.655Z] node_tests_1  |     ^
[2022-11-16T06:55:10.655Z] node_tests_1  |
[2022-11-16T06:55:10.655Z] node_tests_1  | Error: Cannot find module 'node:process'
[2022-11-16T06:55:10.655Z] node_tests_1  |     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
```

The breakage is in this restify file:

```
lib/request.js
5:const { emitWarning } = require('node:process');
```

The "node:" prefix is called "Core modules" (https://nodejs.org/api/modules.html#core-modules). This was added in v16.0.0, v14.18.0.

Restify@9's package.json says `"engines": { "node": ">=10.0.0" }` so the intent might have been to support node v10. I'll open an issue on restify asking about that.

### CODE REVIEW

**Comment by trentm** [comment]
I've opened https://github.com/restify/node-restify/issues/1932 about the "engines" mismatch.

**Comment by trentm** [comment]
run module tests for restify
